### ISSUE TITLE
Training list not always updated correctly

### ISSUE THREAD

**Issue by Caelarius** [DreierF/MyTargets#198] opened 2016-11-27 13:04 UTC
Android 6.01
Mytargets 2.3.5 (latest released version at time of submitting the ticket)

When adding or removing a training, the training list is not always updated correctly. I've seen the following happening:

- After adding a training, the new training was on top of the previous training. This resulted in an unreadable training entry (the trainings below that one were readable). Workaround: Forced a redraw of the list by switching to a different view or exiting and starting the app again (don't remember exactly what I did). Reproducability is low, only saw this once.

- After removing a training, the training remains visible in the list, but with a score of 0/0. Tapping the training at that moment crashes the app. Reproducability is medium, saw this happen a few times. (I used the free training type to add the trainings)

User severity: medium. There's a workaround by forcing a redraw, but tapping a removed training crashes the app.

**Comment by DreierF** [comment] 2016-11-27 13:09
I also saw this issue once after adding a training, but could also not reproduce it. 
Thanks for bringing it up again!
I'll investigate ...

**Comment by DreierF** [comment] 2017-01-11 18:09
I assume the issue is fixed with fff9bed8db73b71053336cdb2039fadc2b5386d0. At least I couldn't trigger it on the current develop version.
@Caelarius If this happens to you again on 2.4.0 feel free to reopen the issue.

**Closed by DreierF** 2017-01-11 18:09 UTC
Labels: bug
