### ISSUE TITLE
unexpected behavior when accidentally submitting an incomplete or empty end

### ISSUE THREAD

**Issue by Tirpitz93** [DreierF/MyTargets#92] opened 2016-06-26 17:02 UTC
app will not allow another end to current round after an empty or incomplete end is submitted.
any new ends are added to the next round and the previous end is not shown

**Comment by Tirpitz93** [comment] 2016-06-27 18:07
perhaps default all arrows to a 0,0 offset miss

**Comment by DreierF** [comment] 2016-06-27 18:10
How did you even manage to submit/save an incomplete end? Normally the end sould only be saved when the end is finished.

**Comment by Tirpitz93** [comment] 2016-06-27 18:42
not sure, added one arrow by mistake, then hit back arrow (top left). Then adding any further ends were put into a new round (which I had not yet created).

**Comment by DreierF** [comment] 2016-09-15 10:37
This was most likely fixed by splitting up TrainingFragment into TrainingFragment and RoundFragment. And since it is not reproducible I will close this issue.

**Closed by DreierF** 2016-09-15 10:37 UTC
Labels: bug, more information needed
