### ISSUE TITLE
Can not import backup on new device

### ISSUE THREAD

**Issue by reox** [DreierF/MyTargets#379] opened 2019-02-09 13:58 UTC
I have a new device and want to import the backup from my old device.
Both App versions are the same (3.0.3 (85)).
I saved the backup on the old device, put the zip file to the new one and imported it there.
The app restarts but the data is not restored.
The only difference is, that the old device is Android 7.1 and the new is Android 9.

Is it not possible to import all the data from the old device?
I checked the data.db and it looks OK. My arrow/bow definitons are in there and also the rounds and shots look ok.

If you need any more information or logfiles, just tell me what to do!

**Comment by cereleste** [comment] 2019-03-01 15:06
Hi, I've got a similar issue, though in my case it's from a Google cloud backup. Google says it has a backup for Mytargets in the correct location, but the app won't access it.

**Comment by bayral** [comment] 2019-07-12 10:03
I had the same issue, I had try with the latest version in beta and the import was ok.

**Comment by DreierF** [comment] 2019-08-04 09:35
I fixed various issues related to backup creation and import in 3.1.0 Beta 4. Closing this for now.

Feel free to create a new issue if the problem is still reproducible with 3.1.0 Beta 4.

Note: You cannot fix an already broken backup. However there is a new option in the Backup screens context menu that attempts to restore as much as possible from a broken backup.

**Closed by DreierF** 2019-08-04 09:35 UTC
